<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Magento\OfflinePayments\Block\Form\Checkmo
 */
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()) ?>" style="display:none">
    <label class="label"><span><?php echo $block->escapeHtml(__('Receiving address will be generated after the submission.')) ?></span></label>
</fieldset>
